language: bash

sudo: false

services:
  - docker

before_script:
  - make image VERSION=test

script:
  - make test VERSION=test

notifications:
  email:
    on_success: never
    on_failure: always
